---
title: "Exlporatory Data Analysis"
output:
  html_notebook: default
  pdf_document: default
---


# Introduction

This notebook follows [R for Data Science](http://r4ds.had.co.nz/exploratory-data-analysis.html) to cover the topic of exploratry data analysis (EDA). To quote from the txt:

> EDA is not a formal process with a strict set of rules. More than anything, EDA  is a state of mind. During the initial phases of EDA you should feel free to investigate every idea that occurs to you. Some of these ideas will pan out, and some will be dead ends. 

The goal of an exploratory data analysis is to gain understanding of your data. There are no hard a fast rules for conducting an EDA but two types of questions will always be useful for making discoveries within your data. You can loosely word these questions as:

1. What type of variation occurs within my variables?

2. What type of covariation occurs between my variables?

The rest of this notebook goes through some typical steps of EDA and demostrates certain useful techniques and commands that are hekpful in carrying out an EDA. 

# Distributions of Variables

We begin by importing some useful R packages. Make sure that you have all of 
them installed before loading them. (Including the results="hide" and warning=FALSE suppresses the output and warnings usually produced by the commands.)
```{r, results="hide", warning=FALSE}
library(tidyverse)
library(fastR2)
```

The **distribution** of a variable in a dataset is the set of possible values that the variable takes on together with the frequency with which each value occurs for that variable. Visualizing the distribution of a variable is an extremely valuable thing to do. The way that a distribution is visualized depends largely on whether the variable is categorical or continuous. If the variable is categorical, a barplot can be used to visualize its distribution. On the other hand, if the variable if continuous a histogram is appropriate but there are also other types of plots that are useful as well. 

# Missing Values


# Relationship Between Variables












































